# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'npm'
          node-version: 22
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Install Playwright Browsers
        run: npx playwright install chromium --only-shell
      - run: npm test -- --forbid-only

  check-ts:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'npm'
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm run check

  lint-code:
    name: Lint code (oxlint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'npm'
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm run lint

  lint-package:
    name: Lint package (publint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'npm'
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Build package
        run: npm run build
      - name: Lint package
        run: npm run lint-package

  npm-audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'npm'
          node-version: 22
      - name: npm audit
        run: npm audit --audit-level=high
